name: fluffer
description: "Application de vote Loup Garou"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  file_picker: ^8.0.0
  font_awesome_flutter: ^10.12.0
  talker_flutter: ^5.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # Optionnel